// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4v7cFsl5rB97CvTuQNa4nMYLP9T3tC4w',
    appId: '1:599762705521:web:8cf96ce83d5cc422298fd0',
    messagingSenderId: '599762705521',
    projectId: 'carebridge-26b75',
    authDomain: 'carebridge-26b75.firebaseapp.com',
    storageBucket: 'carebridge-26b75.firebasestorage.app',
    measurementId: 'G-MTNDTGS331',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZkgeCNYJBEs-agUkYRBRLLqCHshy_E1w',
    appId: '1:599762705521:android:7b9298ad84bf2e99298fd0',
    messagingSenderId: '599762705521',
    projectId: 'carebridge-26b75',
    storageBucket: 'carebridge-26b75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfcB0b86uQqXx3fiv4bmYpOv_Sk_1wy3A',
    appId: '1:599762705521:ios:d27d98a7cbb37ce0298fd0',
    messagingSenderId: '599762705521',
    projectId: 'carebridge-26b75',
    storageBucket: 'carebridge-26b75.firebasestorage.app',
    iosBundleId: 'com.example.careBridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfcB0b86uQqXx3fiv4bmYpOv_Sk_1wy3A',
    appId: '1:599762705521:ios:d27d98a7cbb37ce0298fd0',
    messagingSenderId: '599762705521',
    projectId: 'carebridge-26b75',
    storageBucket: 'carebridge-26b75.firebasestorage.app',
    iosBundleId: 'com.example.careBridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4v7cFsl5rB97CvTuQNa4nMYLP9T3tC4w',
    appId: '1:599762705521:web:20d86c77bc59e03a298fd0',
    messagingSenderId: '599762705521',
    projectId: 'carebridge-26b75',
    authDomain: 'carebridge-26b75.firebaseapp.com',
    storageBucket: 'carebridge-26b75.firebasestorage.app',
    measurementId: 'G-DE9WVLX68H',
  );
}

/*
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkQtirRiDx-hidMOpcaYuEHl9z0NASPWo',
    appId: '1:370206867386:android:c22b64fd1bcd29141f2783',
    messagingSenderId: '370206867386',
    projectId: 'carebridge-5fc45',
    databaseURL:
        'https://carebridge-5fc45-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'carebridge-5fc45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe7mnE7z8ewPSjtZcSj9_7e2TCBttHd4I',
    appId: '1:370206867386:ios:2ebd4c11bdc6c1091f2783',
    messagingSenderId: '370206867386',
    projectId: 'carebridge-5fc45',
    databaseURL:
        'https://carebridge-5fc45-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'carebridge-5fc45.firebasestorage.app',
    iosBundleId: 'com.example.carebridge',
  );
}
*/
